add signing to other workflow as well

diff --git a/.github/actions/docker-build-and-push/action.yaml b/.github/actions/docker-build-and-push/action.yaml
--- a/.github/actions/docker-build-and-push/action.yaml
+++ b/.github/actions/docker-build-and-push/action.yaml
@@ -38,6 +38,9 @@ runs:
         FULL="ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}"
         echo "LOWERCASED=$(echo "$FULL" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
         
+    - name: Install Cosign
+      uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
+        
     - name: Set up QEMU
       uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
 
@@ -64,3 +67,17 @@ runs:
         build-args: ${{ inputs.build-args }}
         provenance: mode=max
         sbom: true
+
+    - name: Sign the image with GitHub OIDC Token
+      shell: bash
+      env:
+        DIGEST: ${{ steps.build.outputs.digest }}
+        IMAGE_TAG: ${{ env.LOWERCASED }}:${{ inputs.image-tag }}
+      run: |
+        if [ -z "$DIGEST" ]; then
+          echo "❌ Digest is empty. Build step may have failed." >&2
+          exit 1
+        fi
+
+        echo "🔐 Signing $IMAGE_TAG@$DIGEST"
+        cosign sign --yes $IMAGE_TAG@$DIGEST
